stages:
  - build
  - test
build website:
  stage: build
  image: node:16-alpine
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build
test website:
  stage: test
  image: alpine
  script:
    - test -f build/index.html
unit test:
  stage: test
  image: node:16-alpine
  script:
    - yarn install
    - yarn test