stages:
  - .pre
  - build
  - test
  - deploy
    
build website:
  stage: build
  image: node:16-alpine
  script:
    - yarn install
    - yarn lint
    - yarn test
    - yarn build
  artifacts:
    paths:
      - build

test website:
  stage: test
  image: node:16-alpine
  script:
    - yarn global add serve
    - apk add curl
    - serve -s build &
    - sleep 10
    - curl http://localhost:3000 | grep "React App"

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli:latest
    entrypoint: [""]
  script:
    - aws --version
    - echo "Hello S3" > test.txt
    - aws s3 sync build s3://$AWS_S3_BUCKET/ --delete