stages:
  - build
  - test
build website:
  stage: build
  image: node:16-alpine
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build
teste website:
  stage: test
  image: alpine
  script:
    - test -f build/intex.html