stages:
  - .pre
  - build
  - test

unit test:
  stage: .pre
  image: node:16-alpine
  script:
    - yarn install
    - yarn test

linter:
  stage: .pre
  image: node:16-alpine
  script:
    - yarn install
    - yarn lint
    
build website:
  stage: build
  image: node:16-alpine
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build

test website:
  stage: test
  image: alpine
  script:
    - test -f build/index.html